USE possystem;
CREATE TABLE banches 
(
	id UNIQUEIDENTIFIER NOT NULL,
	[name] NVARCHAR(100) NOT NULL,
	[phone] VARCHAR(25) NOT NULL DEFAULT '',
	full_address VARCHAR(255) NOT NULL DEFAULT '',
	province INT NOT NULL DEFAULT 0,
	city INT NOT NULL DEFAULT 0,
	district INT NOT NULL DEFAULT 0,
	CONSTRAINT pk_banches PRIMARY KEY CLUSTERED (branch_id),
);
CREATE TABLE categories
(
	categoryId UNIQUEIDENTIFIER NOT NULL,
	[name] NVARCHAR(100) NOT NULL,
	CONSTRAINT pk_categories PRIMARY KEY CLUSTERED (categoryId),
);
CREATE TABLE units
(
	unitId UNIQUEIDENTIFIER NOT NULL,
	[name] NVARCHAR(100) NOT NULL,
	CONSTRAINT pk_units PRIMARY KEY CLUSTERED (unitId),
);
CREATE TABLE racks
(
	rackId UNIQUEIDENTIFIER NOT NULL,
	[name] NVARCHAR(100) NOT NULL,
	branchId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT pk_racks PRIMARY KEY CLUSTERED (rackId),
);
CREATE TABLE users
(
	userId UNIQUEIDENTIFIER NOT NULL,
	[name] VARCHAR(250) NOT NULL DEFAULT '',
	[phone] VARCHAR(25) NOT NULL DEFAULT '',
	[email] VARCHAR(50) NOT NULL DEFAULT '',
	[photo] VARCHAR(255) NOT NULL DEFAULT '',
	[rolename] VARCHAR(50) NOT NULL DEFAULT '',
	CONSTRAINT pk_users PRIMARY KEY CLUSTERED(id)
);
CREATE TABLE opencashiers
(
	branchId UNIQUEIDENTIFIER NOT NULL,
	userId UNIQUEIDENTIFIER NOT NULL,
	openDate DATE NOT NULL,
	amount INT NOT NULL DEFAULT 0,
	CONSTRAINT pk_opencashiers PRIMARY KEY CLUSTERED (branchId, userId, openDate),
);
CREATE TABLE products
(
	productId UNIQUEIDENTIFIER NOT NULL,
	[name] NVARCHAR(100) NOT NULL,
	categoryId UNIQUEIDENTIFIER,
	unitId UNIQUEIDENTIFIER,
	price INT NOT NULL DEFAULT 0,
	CONSTRAINT pk_products PRIMARY KEY CLUSTERED (productId),
);
CREATE TABLE productstocks
(
	branchId UNIQUEIDENTIFIER NOT NULL,
	productId UNIQUEIDENTIFIER NOT NULL,
	stock INT NOT NULL DEFAULT 0,
	CONSTRAINT pk_productstocks PRIMARY KEY CLUSTERED (branchId, productId),
);	