//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astro.DbInitialializer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Astro.DbInitialializer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE countries
        ///(
        ///    `id` SMALLINT NOT NULL,
        ///    `name` VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    `a2code` CHAR(2) NOT NULL DEFAULT &apos;&apos;,
        ///    `a3code` CHAR(3) NOT NULL DEFAULT &apos;&apos;,
        ///    `phoneCode` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
        ///    CONSTRAINT pk_countries PRIMARY KEY (`id`)
        ///);
        ///CREATE TABLE provinces
        ///(
        ///    `id` SMALLINT UNSIGNED NOT NULL,
        ///    `name` VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    `country` SMALLINT NOT NULL DEFAULT 0,
        ///    CONSTRAINT pk_states PRIMARY KEY (`id`)
        ///);
        ///CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddl {
            get {
                return ResourceManager.GetString("ddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO units (name) VALUES
        ///(&apos;pcs&apos;),
        ///(&apos;buah&apos;),
        ///(&apos;bungkus&apos;),
        ///(&apos;pak&apos;),
        ///(&apos;kotak&apos;),
        ///(&apos;karton&apos;),
        ///(&apos;dus&apos;),
        ///(&apos;set&apos;),
        ///(&apos;lusin&apos;),
        ///(&apos;gross&apos;),
        ///(&apos;rim&apos;),
        ///(&apos;sak&apos;),
        ///(&apos;karung&apos;),
        ///(&apos;rol&apos;),
        ///(&apos;botol&apos;),
        ///(&apos;jerigen&apos;),
        ///(&apos;drum&apos;),
        ///(&apos;liter&apos;),
        ///(&apos;mililiter&apos;),
        ///(&apos;kaleng&apos;),
        ///(&apos;tube&apos;),
        ///(&apos;gram&apos;),
        ///(&apos;kilogram&apos;),
        ///(&apos;ons&apos;),
        ///(&apos;kuintal&apos;),
        ///(&apos;ton&apos;),
        ///(&apos;milimeter&apos;),
        ///(&apos;centimeter&apos;),
        ///(&apos;meter&apos;),
        ///(&apos;gulung&apos;),
        ///(&apos;meter persegi&apos;),
        ///(&apos;hektar&apos;),
        ///(&apos;lembar&apos;),
        ///(&apos;batang&apos;),
        ///(&apos;biji&apos;),
        ///(&apos;pasang&apos;),
        ///(&apos;unit&apos;),
        ///(&apos;pack&apos;);
        ///
        ///INSERT I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dml {
            get {
                return ResourceManager.GetString("dml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- countries
        ///CREATE TABLE countries (
        ///    id SMALLINT PRIMARY KEY,
        ///    name VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    a2code CHAR(2) NOT NULL DEFAULT &apos;&apos;,
        ///    a3code CHAR(3) NOT NULL DEFAULT &apos;&apos;,
        ///    phoneCode INTEGER NOT NULL DEFAULT 0
        ///);
        ///
        ///-- provinces
        ///CREATE TABLE provinces (
        ///    id INTEGER PRIMARY KEY,
        ///    name VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    country SMALLINT NOT NULL DEFAULT 0
        ///);
        ///
        ///-- cities
        ///CREATE TABLE cities (
        ///    id INTEGER PRIMARY KEY,
        ///    name VARCHAR(200) NOT NULL DEFAULT &apos;&apos;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string npgsql_ddl {
            get {
                return ResourceManager.GetString("npgsql_ddl", resourceCulture);
            }
        }
    }
}
