//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astro.DbInitialializer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Astro.DbInitialializer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- countries
        ///CREATE TABLE countries (
        ///    country_id SMALLINT PRIMARY KEY,
        ///    country_name VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    country_a2code CHAR(2) NOT NULL DEFAULT &apos;&apos;,
        ///    country_a3code CHAR(3) NOT NULL DEFAULT &apos;&apos;,
        ///    country_phone_code INTEGER NOT NULL DEFAULT 0
        ///);
        ///
        ///-- provinces
        ///CREATE TABLE states (
        ///    state_id SMALLINT PRIMARY KEY,
        ///    state_name VARCHAR(100) NOT NULL DEFAULT &apos;&apos;,
        ///    country_id SMALLINT NOT NULL DEFAULT 0
        ///);
        ///
        ///-- cities
        ///CREATE TABLE cities (
        ///    city_id INTEGER  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddl {
            get {
                return ResourceManager.GetString("ddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO roles (role_name) VALUES (&apos;superadmin&apos;);
        ///INSERT INTO users (user_name, role_id) VALUES (&apos;havas-media.com&apos;, 1);
        ///INSERT INTO units (unit_name) VALUES
        ///(&apos;pcs&apos;),
        ///(&apos;buah&apos;),
        ///(&apos;bungkus&apos;),
        ///(&apos;pak&apos;),
        ///(&apos;kotak&apos;),
        ///(&apos;karton&apos;),
        ///(&apos;dus&apos;),
        ///(&apos;set&apos;),
        ///(&apos;lusin&apos;),
        ///(&apos;gross&apos;),
        ///(&apos;rim&apos;),
        ///(&apos;sak&apos;),
        ///(&apos;karung&apos;),
        ///(&apos;rol&apos;),
        ///(&apos;botol&apos;),
        ///(&apos;jerigen&apos;),
        ///(&apos;drum&apos;),
        ///(&apos;liter&apos;),
        ///(&apos;mililiter&apos;),
        ///(&apos;kaleng&apos;),
        ///(&apos;tube&apos;),
        ///(&apos;gram&apos;),
        ///(&apos;kilogram&apos;),
        ///(&apos;ons&apos;),
        ///(&apos;kuintal&apos;),
        ///(&apos;ton&apos;),
        ///(&apos;milimeter&apos;),
        ///(&apos;centimeter&apos;),
        ///(&apos;meter&apos;), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dml {
            get {
                return ResourceManager.GetString("dml", resourceCulture);
            }
        }
    }
}
